- job:
    name: aodhclient-dsvm-functional
    parent: devstack-tox-functional
    description: |
      Devstack-based functional tests for aodhclient.
    required-projects:
      - openstack/python-aodhclient
      - openstack/aodh
        # We neeed ceilometer's devstack plugin to install gnocchi
      - openstack/ceilometer
      - gnocchixyz/gnocchi
      - openstack-k8s-operators/sg-core
    timeout: 4200
    vars:
      devstack_localrc:
        AODH_SERVICE_HOST: localhost
        AODH_DEPLOY: uwsgi
        CEILOMETER_BACKENDS: "gnocchi,sg-core"
        PROMETHEUS_SERVICE_SCRAPE_TARGETS: prometheus,sg-core
      devstack_plugins:
        aodh: https://opendev.org/openstack/aodh
        ceilometer: https://opendev.org/openstack/ceilometer
        sg-core: https://github.com/openstack-k8s-operators/sg-core

- project:
    queue: telemetry
    templates:
      - check-requirements
      - openstack-python3-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - openstackclient-plugin-jobs
    check:
      jobs:
        - aodhclient-dsvm-functional:
            irrelevant-files: &ac-irrelevant-files
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
              - ^.*\.rst$
              - ^releasenotes/.*$
    gate:
      jobs:
        - aodhclient-dsvm-functional:
            irrelevant-files: *ac-irrelevant-files
