- job:
    name: aodhclient-dsvm-functional
    parent: devstack-tox-functional
    description: |
      Devstack-based functional tests for aodhclient.
    required-projects:
      - openstack/python-aodhclient
      - openstack/aodh
        # We neeed ceilometer's devstack plugin to install gnocchi
      - openstack/ceilometer
      - gnocchixyz/gnocchi
      - openstack-k8s-operators/sg-core
      - openstack/devstack-plugin-prometheus
    timeout: 4200
    vars:
      devstack_localrc:
        CEILOMETER_BACKENDS: "gnocchi,sg-core"
        PROMETHEUS_SERVICE_SCRAPE_TARGETS: prometheus,sg-core
        PROMETHEUS_CUSTOM_SCRAPE_TARGETS: "localhost:3000,localhost:9090"
      devstack_plugins:
        aodh: https://opendev.org/openstack/aodh
        ceilometer: https://opendev.org/openstack/ceilometer
        sg-core: https://github.com/openstack-k8s-operators/sg-core
        devstack-plugin-prometheus: https://opendev.org/openstack/devstack-plugin-prometheus
      devstack_services:
        node_exporter: false
      zuul_copy_output:
        /etc/prometheus/prometheus.yml: logs
        /etc/openstack/prometheus.yaml: logs
      devstack_local_conf:
        post-config:
          $AODH_CONF:
            DEFAULT:
              enable_evaluation_results_metrics: True

- project:
    queue: telemetry
    templates:
      - check-requirements
      - openstack-python3-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - openstackclient-plugin-jobs
    check:
      jobs:
        - aodhclient-dsvm-functional:
            irrelevant-files: &ac-irrelevant-files
              - ^\.gitreview$
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
              - ^doc/.*$
              - ^.*\.rst$
              - ^releasenotes/.*$
    gate:
      jobs:
        - aodhclient-dsvm-functional:
            irrelevant-files: *ac-irrelevant-files
